name: Build and deploy ASP.Net Core app to Azure Web App - bookreviewhub-api

on:
  push:
    branches:
      - master  # or `main` if that's your default
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build API project
        run: dotnet build BookReviewHub.Api/BookReviewHub.Api.csproj --configuration Release

      - name: Publish API project
        run: dotnet publish BookReviewHub.Api/BookReviewHub.Api.csproj -c Release -o ./myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: myapp
          path: myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: myapp

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E71ED0FC56704BC0AF5904F3823B6408 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2C6889A737754BADB0C438D517E73E12 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_170A153D3CA841FB96FEBBC3461C664E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bookreviewhub-api'
          slot-name: 'Production'
          package: 'myapp'
